<?php if (defined('AAM_KEY')) { ?>
    <?php if ( !IS_PROFILE_PAGE && !is_network_admin() && current_user_can('promote_user', $user->ID)) { ?>
        <table class="form-table">
            <tr>
                <th><?php echo esc_html('User Roles', AAM_KEY); ?></th>
                <td>
                    <div class="wp-tab-panel">
                        <ul>
                        <?php foreach (get_editable_roles() as $id => $role) { ?>
                            <li>
                                <label>
                                    <input type="checkbox" name="aam_user_roles[]" value="<?php echo esc_attr($id); ?>" <?php checked(in_array($id, $user->roles)); ?> />
                                    <?php echo esc_html(translate_user_role($role['name'])); ?>
                                </label>
                            </li>
                        <?php } ?>
                        </ul>
                    </div>
                </td>
            </tr>
        </table>

        <!-- Remove standard WordPress roles selector-->
        <script>
            (function($) {
                $(document).ready(function(){
                    $('.user-role-wrap').remove();
                });
            })(jQuery);
        </script>
    <?php } ?>
<?php } ?>