<?php if (defined('AAM_KEY')) { ?>
<tr class="form-field term-access-manager-wrap">
    <th scope="row"><label for="term-access-manager"><?php _e('Access'); ?></label></th>
    <td>
        <?php if (defined('AAM_PLUS_PACKAGE')) { ?>
            <div style="padding: 0px 10px; box-sizing: border-box; background-color: #FFFFFF; width: 95%;">
                <iframe src="<?php echo admin_url('admin.php?page=aam&aamframe=post&oid=' . $args->term->term_id . '|' . $args->term->taxonomy . '&otype=term'); ?>" width="100%" height="450" style="border-bottom: 1px solid #e5e5e5; margin-top:10px;"></iframe>
            </div>
        <?php } else { ?>
            <div style="border-left: 4px solid #ffb900; background-color: #FFF1CC; padding: 10px; font-size: 1em; margin: 10px 0px;">
                In order to manage access to this category for any user, role or visitors please consider to purchase <strong><a href="https://aamplugin.com/extension/plus-package" target="_blank">AAM Plus Package</a></strong> extension for <a href="https://wordpress.org/plugins/advanced-access-manager/" target="_blank">Advanced Access Manager</a> plugin.
            </div>
        <?php } ?>
    </td>
</tr>
<?php }