<?php if (defined('AAM_KEY')) { ?>
    <div class="wrap" id="aam-container">
        <div class="row" id="aam-subject-banner">
            <div class="col-xs-12 col-md-8">
                <div class="aam-current-subject"></div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-8">
                <div class="metabox-holder">
                    <div class="postbox">
                        <h3 class="hndle">
                            <span><?php echo __('Main Panel', AAM_KEY); ?></span>
                        </h3>
                        <div class="inside" id="access-manager-inside">
                            <div class="aam-postbox-inside" id="aam-content">
                                <p class="alert alert-info text-larger text-center" id="aam-initial-load"><?php echo AAM_Backend_View_Helper::preparePhrase('[Loading AAM UI]. Please wait. If content will not load within next 30 seconds, clear your browser cache and reload the page. If still nothing, it is most likely some sort of JavaScript or CSS conflict with one your active plugins or theme. Try to deactivate all plugins and switch to any default WordPress theme to find out what causes the issue.', 'strong'); ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <?php $manageExtensions = AAM_Core_Config::get('core.settings.extensionSupport', true) && current_user_can('aam_manage_extensions'); ?>

            <div class="col-xs-12 col-md-4 aam-sidebar">
                <?php if (AAM_Core_Console::count() && current_user_can('aam_show_notifications')) { ?>
                    <div class="metabox-holder shared-metabox">
                        <div class="postbox">
                            <h3 class="hndle text-danger">
                                <i class='icon-attention-circled'></i> <span><?php echo __('Notifications', AAM_KEY); ?></span>
                            </h3>
                            <div class="inside">
                                <div class="aam-postbox-inside">
                                    <ul class="aam-error-list">
                                        <?php foreach (AAM_Core_Console::getAll() as $message) { ?>
                                            <li><?php echo $message; ?></li>
                                        <?php } ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                
                <div class="metabox-holder shared-metabox">
                    <div class="postbox">
                        <div class="inside">
                            <div class="aam-social">
                                <a href="#" title="Access" data-type="main" class="aam-area text-danger">
                                    <i class="icon-cog-alt"></i>
                                    <span>Access</span>
                                </a>
                                <?php if (current_user_can('aam_manage_settings')) { ?>
                                    <a href="#" title="Settings" data-type="settings" class="aam-area">
                                        <i class="icon-wrench"></i>
                                        <span>Settings</span>
                                    </a>
                                <?php } ?>
                                <?php if ($manageExtensions) { ?>
                                    <a href="#" title="Extensions" data-type="extensions" class="aam-area">
                                        <i class="icon-cubes"></i>
                                        <span>Extensions</span>
                                    </a>
                                <?php } ?>
                                <?php if (current_user_can('aam_view_help_btn')) { ?>
                                    <a href="https://aamplugin.com/support" title="Help" target="_blank">
                                        <i class="icon-help-circled"></i>
                                        <span>Help</span>
                                    </a>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <?php if (current_user_can('aam_manage_settings')) { ?>
                    <div class="metabox-holder settings-metabox" style="display:none;">
                        <div class="postbox">
                            <div class="inside">
                                <div class="row">
                                    <div class="col-xs-12 col-md-6">
                                        <a href="#" class="btn btn-primary btn-block" id="clear-cache"><?php echo __('Clear AAM Cache', AAM_KEY); ?></a>
                                    </div>
                                    <div class="col-xs-12 col-md-6">
                                        <a href="#clear-settings-modal" data-toggle="modal" class="btn btn-danger btn-block"><?php echo __('Reset AAM Settings', AAM_KEY); ?></a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" id="clear-settings-modal" tabindex="-1" role="dialog">
                            <div class="modal-dialog modal-sm" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title"><?php echo __('Clear all settings', AAM_KEY); ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <p class="text-center alert alert-danger text-larger"><?php echo __('All AAM settings will be removed.', AAM_KEY); ?></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" id="clear-settings"><?php echo __('Clear', AAM_KEY); ?></button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Cancel', AAM_KEY); ?></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                
                <?php if (AAM_Extension_Repository::getInstance()->isWriteableDirectory() === false && $manageExtensions) { ?>
                    <?php $relativePath = AAM_Extension_Repository::getInstance()->getBasedir(true); ?>
                    <div class="metabox-holder extensions-metabox" id='extension-dir-warning' style="display:none;">
                        <div class="postbox">
                            <h3 class="hndle warning">
                                <span><?php echo __('Warning', AAM_KEY); ?></span>
                            </h3>
                            <div class="inside">
                                <div class="aam-postbox-inside text-center">
                                    <p class='alert alert-warning text-larger highlighted-italic'>
                                        <?php echo sprintf(AAM_Backend_View_Helper::preparePhrase('All AAM extension should be located in [%s] directory however it either does not exist or is not writable.', 'b'), $relativePath); ?>
                                    </p>
                                    <a href="#" class="btn btn-sm btn-success btn-block" id='fix-extension-dir-issue'><i class="icon-wrench"></i> <?php echo __('Click To Fix The Issue', AAM_KEY); ?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                
                    <div class="modal fade" id="extension-dir-issue-modal" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <div class="form-group">
                                        <p class="alert alert-warning text-larger">
                                            <?php echo sprintf(AAM_Backend_View_Helper::preparePhrase('Failed to create a [%s] directory for AAM extension. To create it manually, login to your website via FTP and create [%s] directory. [Please Note!] It is a relative directory path from your website root (where wp-config.php file is located).', 'b', 'b', 'b'), $relativePath, $relativePath); ?>
                                        </p>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Ok', AAM_KEY); ?></button>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                
                <?php $licenses = AAM_Extension_Repository::getInstance()->getCommercialLicenses(); ?>
                <?php if (count($licenses) && $manageExtensions) { ?>
                    <div class="metabox-holder extensions-metabox" style="display:none;">
                        <div class="postbox">
                            <h3 class="hndle">
                                <span><?php echo __('Premium Licenses', AAM_KEY); ?></span>
                            </h3>
                            <div class="inside">
                                <div class="aam-postbox-inside">
                                    <table class="table table-striped table-bordered">
                                        <tbody>
                                        <?php foreach($licenses as $license) { ?>
                                            <tr>
                                                <td width="70%">
                                                    <b><?php echo $license['extension']; ?></b><br/>
                                                    <small>License: <?php echo $license['license']; ?></small>
                                                    <?php if (!empty($license['expires'])) { ?>
                                                    <br/> <small>Expires: <?php echo $license['expires']; ?></small>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <div class="aam-row-actions">
                                                        <a href="https://aamplugin.com/license/<?php echo $license['license']; ?>" class="aam-row-action"><i class="icon-cog text-success" data-toggle="tooltip" title="<?php echo __('Manage License', AAM_KEY); ?>"></i></a>
                                                        <?php if (!empty($license['expires'])) { ?>
                                                        <a href="https://aamplugin.com/upgrade/<?php echo $license['license']; ?>" data-toggle="tooltip" title="<?php echo __('Upgrade License', AAM_KEY); ?>" class="aam-row-action" target="_blank"><i class="icon-angle-circled-up text-success"></i></a>
                                                        <?php } ?>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                
                <div class="metabox-holder extensions-metabox" style="display:none;">
                    <div class="postbox">
                        <div class="inside">
                            <div class="aam-postbox-inside text-center">
                                <p class="alert alert-info text-larger highlighted-italic"><?php echo AAM_Backend_View_Helper::preparePhrase('The [Development Package] allows you to get all premium extensions for [unlimited number of websites].', 'i', 'b'); ?></p>
                                <a href="https://aamplugin.com/development-package" target="_blank" class="btn btn-sm btn-primary btn-block"><i class="icon-link"></i> <?php echo __('Read More', AAM_KEY); ?></a>
                            </div>
                        </div>
                    </div>
                </div>
                
                <?php if (is_network_admin() && !defined('AAM_MULTISITE')) { ?>
                    <div class="metabox-holder main-metabox">
                        <div class="postbox">
                            <h3 class="hndle text-warning">
                                <i class='icon-attention-circled'></i> <span><?php echo __('AAM Multisite', AAM_KEY); ?></span>
                            </h3>
                            <div class="inside">
                                <p class="aam-info"><?php echo AAM_Backend_View_Helper::preparePhrase('Install free [AAM Multisite extension] in order to manage all your sites from the Network Admin.', 'b'); ?></p>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                
                <?php do_action('aam-sidebar-ui-action', 'top'); ?>

                <div class="metabox-holder main-metabox">
                    <div class="postbox">
                        <h3 class="hndle">
                            <span><?php echo __('Users/Roles Manager', AAM_KEY); ?></span>
                            <span class="aam-help-menu" data-target="#user-role-manager-inside"><i class="icon-help-circled"></i></span>
                        </h3>
                        <div class="inside" id="user-role-manager-inside">
                            <div class="aam-postbox-inside">
                                <ul class="nav nav-tabs" role="tablist">
                                    <?php $active = 0; ?>
                                    <?php if (current_user_can('aam_manage_roles') || current_user_can('aam_list_roles')) { ?>
                                        <li role="presentation" class="<?php echo (!$active++ ? 'active ' : ''); ?>text-center"><a href="#roles" aria-controls="roles" role="tab" data-toggle="tab"><i class="icon-users"></i><br/><?php echo __('Roles', AAM_KEY); ?></a></li>
                                    <?php } ?>
                                    <?php if (current_user_can('aam_manage_users') || current_user_can('list_users')) { ?>
                                        <li role="presentation" class="<?php echo (!$active++ ? 'active ' : ''); ?>text-center"><a href="#users" aria-controls="users" role="tab" data-toggle="tab"><i class="icon-user"></i><br/><?php echo __('Users', AAM_KEY); ?></a></li>
                                    <?php } ?>
                                    <?php if (current_user_can('aam_manage_visitors')) { ?>
                                        <li role="presentation" class="<?php echo (!$active++ ? 'active ' : ''); ?>text-center"><a href="#visitor" aria-controls="visitor" role="tab" data-toggle="tab"><i class="icon-user-secret"></i><br/><?php echo __('Visitor', AAM_KEY); ?></a></li>
                                    <?php } ?>
                                    <?php if (current_user_can('aam_manage_default')) { ?>
                                        <li role="presentation" class="<?php echo (!$active++ ? 'active ' : ''); ?>text-center"><a href="#default" aria-controls="default" role="tab" data-toggle="tab" class="text-danger"><i class="icon-asterisk"></i><br/><?php echo __('Default', AAM_KEY); ?></a></li>
                                    <?php } ?>
                                    <?php if ($active === 0) { ?>
                                        <li role="presentation" class="active text-center"><a href="#none" aria-controls="none" role="tab" data-toggle="tab" class="text-muted"><i class="icon-asterisk"></i><br/><?php echo __('None', AAM_KEY); ?></a></li>
                                    <?php } ?>
                                </ul>
                                <div class="tab-content">
                                    <?php $active = 0; ?>
                                    <?php if (current_user_can('aam_manage_roles') || current_user_can('aam_list_roles')) { ?>
                                    <div role="tabpanel" class="tab-pane<?php echo (!$active++ ? ' active' : ''); ?>" id="roles">
                                        <table id="role-list" class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Users</th>
                                                    <th width="65%"><?php echo __('Role', AAM_KEY); ?></th>
                                                    <th><?php echo __('Action', AAM_KEY); ?></th>
                                                    <th>Level</th>
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>

                                        <div class="modal fade" id="add-role-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Create Role', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label><?php echo __('Role Name', AAM_KEY); ?><span class="aam-asterix">*</span></label>
                                                            <input type="text" class="form-control" name="name" placeholder="<?php echo __('Enter Role Name', AAM_KEY); ?>" />
                                                        </div>
                                                        <?php /* TODO: Rethink this filter */ do_action('aam-add-role-ui-action'); ?>
                                                        <?php /* TODO: Rethink this filter */ echo apply_filters('aam-add-role-ui-filter', AAM_Backend_View::getInstance()->loadPartial('role-inheritance.phtml')); ?>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-success" id="add-role-btn"><?php echo __('Create', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="modal fade" id="edit-role-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Update Role', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label for="new-role-name"><?php echo __('Role Name', AAM_KEY); ?></label>
                                                            <input type="text" class="form-control" id="edit-role-name" placeholder="<?php echo __('Enter Role Name', AAM_KEY); ?>" name="name" />
                                                        </div>
                                                        <?php /* TODO: Rethink this filter */ do_action('aam-edit-role-ui-action'); ?>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-success" id="edit-role-btn"><?php echo __('Update', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="modal fade" id="delete-role-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Delete Role', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="text-center aam-confirm-message alert alert-danger" data-message="<?php echo __('Are you sure that you want to delete the %s role?', AAM_KEY); ?>"></p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-danger" id="delete-role-btn"><?php echo __('Delete', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <?php if (current_user_can('aam_manage_users') || current_user_can('list_users')) { ?>
                                    <div role="tabpanel" class="tab-pane<?php echo (!$active++ ? ' active' : ''); ?>" id="users">
                                        <table id="user-list" class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Roles</th>
                                                    <th width="60%"><?php echo __('Username', AAM_KEY); ?></th>
                                                    <th><?php echo __('Action', AAM_KEY); ?></th>
                                                    <th>Level</th>
                                                    <th>Expiration</th>
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>
                                        
                                        <div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?php echo __('Manage User', AAM_KEY); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <ul class="nav nav-tabs" role="tablist">
                                                          <li role="presentation" class="active"><a href="#edit-user-expiration" aria-controls="edit-user-expiration" role="tab" data-toggle="tab">Temporary Access</a></li>
                                                          <li role="presentation"><a href="#edit-user-profile" aria-controls="edit-user-profile" role="tab" data-toggle="tab">Edit User</a></li>
                                                        </ul>

                                                        <div class="tab-content">
                                                            <div role="tabpanel" class="tab-pane active" id="edit-user-expiration">
                                                                <p class="aam-info"><?php echo __('Define for how long user can access the website and what action needs to be taken after access expires.', AAM_KEY); ?>
                                                                
                                                                <div class="form-group aam-bordered">
                                                                    <div id="user-expiration-datapicker"></div>
                                                                    <input type="hidden" id="user-expires" />
                                                                </div>

                                                                <div class="aam-bordered">
                                                                    <div class="form-group">
                                                                        <label><?php echo __('Action After Expiration', AAM_KEY); ?> </label>
                                                                        <select class="form-control" id="action-after-expiration">
                                                                            <option value=""><?php echo __('Select Action', AAM_KEY); ?></option>
                                                                            <option value="logout"><?php echo __('Logout User', AAM_KEY); ?></option>
                                                                            <option value="delete"><?php echo __('Delete Account', AAM_KEY); ?></option>
                                                                            <option value="lock"><?php echo __('Lock Account', AAM_KEY); ?></option>
                                                                            <option value="change-role"><?php echo __('Change User Role', AAM_KEY); ?></option>
                                                                        </select>
                                                                    </div>

                                                                    <div class="form-group hidden" id="expiration-change-role-holder">
                                                                        <label><?php echo __('Change To Role', AAM_KEY); ?></label>
                                                                        <select class="form-control" id="expiration-change-role">
                                                                            <option value=""><?php echo __('Select Role', AAM_KEY); ?></option>
                                                                        </select>
                                                                    </div>
                                                                </div>

                                                                <?php if (AAM::api()->getConfig('core.settings.jwtAuthentication', true) && current_user_can('aam_manage_jwt')) { ?>
                                                                    <div class="form-group aam-bordered aam-outer-top-xs">
                                                                        <label for="login-url-preview" class="aam-block">
                                                                            <?php echo __('Login with URL', AAM_KEY); ?>
                                                                            <a href="#" class="aam-copy-clipboard" data-clipboard-target="#login-url-preview"><?php echo __('Copy to clipboard', AAM_KEY); ?></a>
                                                                        </label>
                                                                        <div class="input-group">
                                                                            <input type="text" class="form-control" id="login-url-preview" data-url="<?php echo add_query_arg('aam-jwt', '%s', site_url()); ?>" value="<?php echo __('Login URL has not been requested', AAM_KEY); ?>" readonly />
                                                                            <span class="input-group-btn">
                                                                                <a href="#" class="btn btn-primary" id="request-login-url"><?php echo __('Request URL', AAM_KEY); ?></a>
                                                                            </span>
                                                                            <input type="hidden" id="login-jwt" />
                                                                        </div>
                                                                        <small><?php echo AAM_Backend_View_Helper::preparePhrase('With this URL user will be automatically logged in until defined date and time. The JWT token associated with URL is [revokable] however not [refreshable].', 'i', 'i'); ?></small>
                                                                    </div>
                                                                <?php } ?>
                                                            </div>
                                                            <div role="tabpanel" class="tab-pane" id="edit-user-profile">
                                                                <p class="aam-info"><?php echo __("To manage user profile, click on the button below.", AAM_KEY); ?></p>
                                                                <p class="text-center">
                                                                    <a href="#" id="edit-user-link" class="btn btn-primary" target="_blank"><?php echo __('Edit User Profile', AAM_KEY); ?></a>
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-warning hidden" id="reset-user-expiration-btn"><?php echo __('Reset', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-success" id="edit-user-expiration-btn"><?php echo __('Save', AAM_KEY); ?></button>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <?php if (current_user_can('aam_manage_visitors')) { ?>
                                    <div role="tabpanel" class="tab-pane<?php echo (!$active++ ? ' active' : ''); ?>" id="visitor">
                                        <div class="visitor-message">
                                            <span class="aam-bordered"><?php echo __('Manage access to your website for visitors (any user that is not authenticated)', AAM_KEY); ?>.</span>
                                            <button class="btn btn-primary btn-block" id="manage-visitor"><i class="icon-cog"></i> <?php echo __('Manage Visitors', AAM_KEY); ?></button>
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <?php if (current_user_can('aam_manage_default')) { ?>
                                    <div role="tabpanel" class="tab-pane<?php echo (!$active++ ? ' active' : ''); ?>" id="default">
                                        <div class="visitor-message">
                                            <span class="aam-bordered"><?php echo __('Manage default access to your website resources for all users, roles and visitor. This includes Administrator role and your user', AAM_KEY); ?>.</span>
                                            <button class="btn btn-danger btn-block" id="manage-default"><i class="icon-cog"></i> <?php echo __('Manage Default Access', AAM_KEY); ?></button>
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <?php if ($active === 0) { ?>
                                    <div role="tabpanel" class="tab-pane active" id="none">
                                        <p class="alert alert-warning"><?php echo __('You are not allowed to manage any of the existing users, roles, visitors or default access settings for all.', AAM_KEY); ?></p>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="aam-help-context">
                                <p class="aam-info aam-hint">
                                    <?php echo AAM_Backend_View_Helper::preparePhrase('Manage access for your users, roles and visitors. Be careful with [Administrator] role as well as your admin user. [Database backup is strongly recommended].', 'b', 'b'); ?>
                                </p>

                                <p class="text-justify">
                                    <strong><i class="icon-users"></i> <?php echo __('Roles', AAM_KEY); ?></strong><br/>
                                    <?php echo __('With Roles tab you can manage access for any defined role, edit role\'s name, create new role or even delete existing (but only when there is no users assigned to it). You are not allowed to delete Administrator role.', AAM_KEY); ?>
                                </p>

                                <p class="text-justify">
                                    <strong><i class="icon-user"></i> <?php echo __('Users', AAM_KEY); ?></strong><br/>
                                    <?php echo __('Manage access for any user. As a bonus feature, you can block user. It means that user will be not able to login to your website anymore.', AAM_KEY); ?>
                                </p>

                                <p class="text-justify">
                                    <strong><i class="icon-user-secret"></i> <?php echo __('Visitor', AAM_KEY); ?></strong><br/>
                                    <?php echo __('Visitor can be considered any user that is not authenticated to your website.', AAM_KEY); ?>
                                </p>
                                
                                <p class="text-justify">
                                    <strong><i class="icon-asterisk"></i> <?php echo __('Default', AAM_KEY); ?></strong><br/>
                                    <?php echo __('Manage default access settings to your website resources for all users, roles and visitors.', AAM_KEY); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                
                <?php do_action('aam-sidebar-ui-action', 'bottom'); ?>
            </div>
        </div>
    </div>
<?php }