<?php if (defined('AAM_KEY')) { ?>
    <div class="row">
        <div class="col-xs-12">
            <p class="aam-notification" data-dynamic-post-label="<?php echo AAM_Backend_View_Helper::preparePhrase('Manage default access to all your %s and %s Categories. This feature is available only with [AAM Plus Package] extension. But you can still manage access to individual %s but only up to 10 %s. Consider to purchase [AAM Plus Package] extension.', 'b', 'b'); ?>"></p>
        </div>
    </div>
<?php }