<?php if (!defined('AAM_KEY')) { exit; } ?>

<?php $frontendOptions = AAM_Backend_Feature_Main_Post::getAccessOptionList('frontend'); ?>
<?php $backendOptions = AAM_Backend_Feature_Main_Post::getAccessOptionList('backend'); ?>
<?php $apiOptions = AAM_Backend_Feature_Main_Post::getAccessOptionList('api'); ?>

<div class="panel-group" id="post-access-accordion" role="tablist" aria-multiselectable="true">
    <?php if (count($frontendOptions) && AAM_Core_Config::get('core.settings.frontendAccessControl', true)) { ?>
        <div class="panel panel-success">
            <div class="panel-heading" role="tab" id="heading-post-frontend-access-settings">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#post-access-accordion" href="#post-frontend-access-settings" aria-expanded="true" aria-controls="post-frontend-access-settings">
                        <i class="icon-doc-text-inv"></i> <strong><?php echo __('Frontend Access Settings', AAM_KEY); ?></strong>
                    </a>
                </h4>
            </div>
            <div id="post-frontend-access-settings" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-post-frontend-access-settings">
                <div class="panel-body">
                    <table class="table table-striped table-bordered">
                        <tbody>
                            <?php foreach ($frontendOptions as $option => $data) { ?>
                                <tr>
                                    <?php $id = uniqid('aam'); ?>
                                    <td width="90%">
                                        <strong class="aam-block aam-highlight text-uppercase"><?php echo $data['title']; ?></strong>
                                        <?php if (!empty($data['sub'])) { ?>
                                            <small class="aam-small-highlighted">
                                                <?php echo $data['sub']; ?>: <b id="<?php echo $data['preview']; ?>" data-ref="<?php echo $data['option']; ?>" class="option-preview">...</b> 
                                                <a href="#<?php echo $data['modal']; ?>" data-toggle="modal" class="advanced-post-option" data-ref="<?php echo $data['option']; ?>" data-preview="#<?php echo $data['preview']; ?>" id="<?php echo $id; ?>"><?php echo __('change', AAM_KEY); ?></a>
                                            </small>
                                        <?php } ?>
                                        <p class="aam-hint" data-dynamic-post-label="<?php echo $data['descr']; ?>"></p>
                                    </td>
                                    <td>
                                        <div class="aam-row-actions">
                                            <i class="aam-row-action text-muted icon-check-empty" data-property="frontend.<?php echo $option; ?>" <?php echo (!empty($data['sub']) ? 'data-trigger="' . $id . '"' : ''); ?>></i>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <?php } ?>

    <?php if (count($backendOptions) && AAM_Core_Config::get('core.settings.backendAccessControl', true)) { ?>
        <div class="panel panel-info">
            <div class="panel-heading" role="tab" id="heading-post-backend-access-settings">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#post-access-accordion" href="#post-backend-access-settings" aria-expanded="false" aria-controls="post-backend-access-settings">
                        <i class="icon-doc-text-inv"></i> <strong><?php echo __('Backend Access Settings', AAM_KEY); ?></strong>
                    </a>
                </h4>
            </div>
            <div id="post-backend-access-settings" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-post-backend-access-settings">
                <div class="panel-body">
                    <table class="table table-striped table-bordered">
                        <tbody>
                            <?php foreach ($backendOptions as $option => $data) { ?>
                                <tr>
                                    <?php $id = uniqid('aam'); ?>
                                    <td width="90%">
                                        <strong class="aam-block aam-highlight text-uppercase"><?php echo $data['title']; ?></strong>
                                        <?php if (!empty($data['sub'])) { ?>
                                            <small class="aam-small-highlighted">
                                                <?php echo $data['sub']; ?>: <b id="<?php echo $data['preview']; ?>" data-ref="<?php echo $data['option']; ?>" class="option-preview">...</b> 
                                                <a href="#modal-<?php echo str_replace('.', '-', $data['option']); ?>" data-toggle="modal" class="advanced-post-option" data-ref="<?php echo $data['option']; ?>" data-preview="#<?php echo $data['preview']; ?>" id="<?php echo $id; ?>"><?php echo __('change', AAM_KEY); ?></a>
                                            </small>
                                        <?php } ?>
                                        <p class="aam-hint" data-dynamic-post-label="<?php echo $data['descr']; ?>"></p>
                                    </td>
                                    <td>
                                        <div class="aam-row-actions">
                                            <i class="aam-row-action text-muted icon-check-empty" data-property="backend.<?php echo $option; ?>" <?php echo (!empty($data['sub']) ? 'data-trigger="' . $id . '"' : ''); ?>></i>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <?php } ?>

    <?php if (count($apiOptions) && AAM_Core_Config::get('core.settings.apiAccessControl', true)) { ?>
        <div class="panel panel-warning">
            <div class="panel-heading" role="tab" id="heading-post-api-access-settings">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#post-access-accordion" href="#post-api-access-settings" aria-expanded="false" aria-controls="post-backend-access-settings">
                        <i class="icon-doc-text-inv"></i> <strong><?php echo __('API Access Settings', AAM_KEY); ?></strong>
                    </a>
                </h4>
            </div>
            <div id="post-api-access-settings" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-post-api-access-settings">
                <div class="panel-body">
                    <table class="table table-striped table-bordered">
                        <tbody>
                            <?php foreach ($apiOptions as $option => $data) { ?>
                                <tr>
                                    <?php $id = uniqid('aam'); ?>
                                    <td width="90%">
                                        <strong class="aam-block aam-highlight text-uppercase"><?php echo $data['title']; ?></strong>
                                        <?php if (!empty($data['sub'])) { ?>
                                            <small class="aam-small-highlighted">
                                                <?php echo $data['sub']; ?>: <b id="<?php echo $data['preview']; ?>" data-ref="<?php echo $data['option']; ?>" class="option-preview">...</b> 
                                                <a href="#<?php echo $data['modal']; ?>" data-toggle="modal" class="advanced-post-option" data-ref="<?php echo $data['option']; ?>" data-preview="#<?php echo $data['preview']; ?>" id="<?php echo $id; ?>"><?php echo __('change', AAM_KEY); ?></a>
                                            </small>
                                        <?php } ?>
                                        <p class="aam-hint" data-dynamic-post-label="<?php echo $data['descr']; ?>"></p>
                                    </td>
                                    <td>
                                        <div class="aam-row-actions">
                                            <i class="aam-row-action text-muted icon-check-empty" data-property="api.<?php echo $option; ?>" <?php echo (!empty($data['sub']) ? 'data-trigger="' . $id . '"' : ''); ?>></i>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <?php } ?>
</div>