<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="post-content">
        <?php if (!defined('AAM_PLUS_PACKAGE')) { ?>
            <div class="row">
                <div class="col-xs-12">
                    <p class="aam-notification">
                        <?php echo sprintf(AAM_Backend_View_Helper::preparePhrase('You are allowed to manage access to unlimited number of posts, pages or custom post types but only for any role, user or visitor. Consider to purchase %s[AAM Plus Package]%s extension to have the ability to also manage access to categories and custom taxonomies or to define the default access to all posts, pages or custom post types. For more information about this functionality check %sHow to manage access to the WordPress content%s.', 'b'), '<a href="https://aamplugin.com/extension/plus-package" target="_blank">', '</a>', '<a href="https://aamplugin.com/article/manage-access-to-the-wordpress-posts-and-terms" target="_blank">', '</a>'); ?>
                    </p>
                </div>
            </div>
        <?php } else { ?>
            <div class="row">
                <div class="col-xs-12">
                    <p class="aam-info">
                        <?php echo sprintf(__('Manage access to posts, pages, custom post types, categories or custom hierarchical taxonomies. For more information about this functionality check %sManage access to the WordPress Posts and Terms%s article.'), '<a href="https://aamplugin.com/article/manage-access-to-the-wordpress-posts-and-terms" target="_blank">', '</a>'); ?>
                    </p>
                </div>
            </div>
        <?php } ?>

        <?php if (defined('AAM_PLUS_PACKAGE') || AAM_Backend_Subject::getInstance()->getUID() != AAM_Core_Subject_Default::UID) { ?>
            <?php $current = $this->getCurrentObject();?>

            <div class="aam-post-breadcrumb">
                <a href="#" data-level="root"><i class="icon-home"></i> <?php echo __('Root', AAM_KEY); ?></a>
                <?php if ($current->id) { ?>
                    <span>
                        <i class="icon-angle-double-right"></i>
                        <?php echo ($current->type == 'post' ? $current->post->post_title : $current->term->name); ?>
                    </span>
                <?php } ?>
            </div>

            <div class="aam-overwrite hidden" id="post-overwritten">
                <span><i class="icon-check"></i> <?php echo __('Settings are customized', AAM_KEY); ?></span>
                <span><a href="#" id="post-reset" class="btn btn-xs btn-primary"><?php echo __('Reset To Default', AAM_KEY); ?></a></span>
            </div>
        
            <?php if ($current->id) { ?>
                <input type="hidden" id="load-post-object" value="<?php echo ($current->type == 'post' ? $current->post->ID : $current->term->term_id); ?>" />
                <input type="hidden" id="load-post-object-type" value="<?php echo $current->type; ?>" />
            <?php } ?>

            <div class="aam-container">
                <table id="post-list" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Link</th>
                            <th width="5%">&nbsp;</th>
                            <th width="75%"><?php echo __('Title', AAM_KEY); ?></th>
                            <th><?php echo __('Actions', AAM_KEY); ?></th>
                            <th>Parent</th>
                            <th>Overwritten</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

                <div class="aam-slide-form aam-access-form" data-type="type">
                    <a href="#" class="btn btn-xs btn-primary post-back btn-right">&Lt; <?php echo __('Go Back', AAM_KEY); ?></a>
                    <span class="aam-clear"></span>
                    <?php /* TODO: Rethink this filter */ echo apply_filters('aam-post-type-ui-filter', AAM_Backend_View::getInstance()->loadPartial('post-type.phtml')); ?>
                    <a href="#" class="btn btn-xs btn-primary post-back">&Lt; <?php echo __('Go Back', AAM_KEY); ?></a>
                </div>

                <div class="aam-slide-form aam-access-form" data-type="term">
                    <a href="#" class="btn btn-xs btn-primary post-back btn-right">&Lt; <?php echo __('Go Back', AAM_KEY); ?></a>
                    <span class="aam-clear"></span>
                    <?php /* TODO: Rethink this filter */ echo apply_filters('aam-term-type-ui-filter', AAM_Backend_View::getInstance()->loadPartial('term-type.phtml')); ?>
                    <a href="#" class="btn btn-xs btn-primary post-back">&Lt; <?php echo __('Go Back', AAM_KEY); ?></a>
                </div>
                
                <?php $frontendOptions = $this->getAccessOptionList('frontend'); ?>
                <?php $backendOptions = $this->getAccessOptionList('backend'); ?>
                <?php $apiOptions = $this->getAccessOptionList('api'); ?>

                <div class="aam-slide-form aam-access-form" data-type="post">
                    <a href="#" class="btn btn-xs btn-primary post-back btn-right">&Lt; <?php echo __('Go Back', AAM_KEY); ?></a>
                    <span class="aam-clear"></span>
                    
                    <?php echo $this->renderAccessForm(); ?>

                    <a href="#" class="btn btn-xs btn-primary post-back">&Lt; <?php echo __('Go Back', AAM_KEY); ?></a>
                </div>
            </div>
        <?php } ?>
                
        <?php require dirname(__FILE__) . '/../partial/post-advanced-settings.phtml'; ?>
    </div>
<?php }