<fieldset>
    <p><label><input type="radio" name="content" value="aam" /> <?php _e('AAM Settings'); ?></label></p>
    <ul id="aam-filters" class="export-filters">
        <li>
            <label><span class="label-responsive" style="font-weight: 500;"><?php _e('System Settings:'); ?></span></label><br/>
            <ul style="margin: 5px 0 0 15px;">
                <li><input type="checkbox" name="export[system][]" value="roles" /> Roles &amp; Capabilities</li>
                <li><input type="checkbox" name="export[system][]" value="utilities" /> AAM Settings</li>
                <li><input type="checkbox" name="export[system][]" value="configpress" /> ConfigPress</li>
            </ul>
        </li>
        <li>
            <label><span class="label-responsive" style="font-weight: 500;"><?php _e('Role Settings:'); ?></span></label><br/>
            <ul style="margin: 5px 0 0 15px;">
                <li><input type="checkbox" name="export[roles][]" value="menu" /> Backend Menu</li>
                <li><input type="checkbox" name="export[roles][]" value="toolbar" /> Top Admin Toolbar</li>
                <li><input type="checkbox" name="export[roles][]" value="metabox" /> Metaboxes &amp; Widgets</li>
                <li><input type="checkbox" name="export[roles][]" value="post" /> Posts &amp; Terms</li>
                <li><input type="checkbox" name="export[roles][]" value="redirect" /> Redirects</li>
                <li><input type="checkbox" name="export[roles][]" value="route" /> API Routes</li>
            </ul>
        </li>
        <li>
            <label><span class="label-responsive" style="font-weight: 500;"><?php _e('User Settings:'); ?></span></label><br/>
            <ul style="margin: 5px 0 0 15px;">
                <li><input type="checkbox" name="export[users][]" value="menu" /> Backend Menu</li>
                <li><input type="checkbox" name="export[users][]" value="toolbar" /> Top Admin Toolbar</li>
                <li><input type="checkbox" name="export[users][]" value="metabox" /> Metaboxes &amp; Widgets</li>
                <li><input type="checkbox" name="export[users][]" value="capability" /> Capabilities</li>
                <li><input type="checkbox" name="export[users][]" value="post" /> Posts &amp; Terms</li>
                <li><input type="checkbox" name="export[users][]" value="redirect" /> Redirects</li>
                <li><input type="checkbox" name="export[users][]" value="route" /> API Routes</li>
            </ul>
        </li>
        <li>
            <label><span class="label-responsive" style="font-weight: 500;"><?php _e('Visitor Settings:'); ?></span></label><br/>
            <ul style="margin: 5px 0 0 15px;">
                <li><input type="checkbox" name="export[visitor][]" value="metabox" /> Frontend Widgets</li>
                <li><input type="checkbox" name="export[visitor][]" value="post" /> Posts &amp; Terms</li>
                <li><input type="checkbox" name="export[visitor][]" value="redirect" /> Redirects</li>
                <li><input type="checkbox" name="export[visitor][]" value="route" /> API Routes</li>
            </ul>
        </li>
        <li>
            <label><span class="label-responsive" style="font-weight: 500;"><?php _e('Default Settings:'); ?></span></label><br/>
            <ul style="margin: 5px 0 0 15px;">
                <li><input type="checkbox" name="export[default][]" value="menu" /> Backend Menu</li>
                <li><input type="checkbox" name="export[default][]" value="toolbar" /> Top Admin Toolbar</li>
                <li><input type="checkbox" name="export[default][]" value="metabox" /> Metaboxes &amp; Widgets</li>
                <li><input type="checkbox" name="export[default][]" value="post" /> Posts &amp; Terms</li>
                <li><input type="checkbox" name="export[default][]" value="redirect" /> Redirects</li>
                <li><input type="checkbox" name="export[default][]" value="route" /> API Routes</li>
            </ul>
        </li>
    </ul>
</fieldset>
<script type="text/javascript">
    jQuery(document).ready(function($){
        var form = $('#export-filters');
        
        form.find('input:radio').change(function() {
            if ($(this).val() === 'aam') {
                $('#aam-filters').slideDown();
            }
        });
    });
</script>